name: pulseaudio
description: "This repository contains a Dart client library to interact with PulseAudio, a sound server that provides a sound system for POSIX systems."
version: 0.0.8
homepage: https://github.com/free-explorers/pulseaudio.dart
repository: https://github.com/free-explorers/pulseaudio.dart

environment:
  sdk: ^3.5.1
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^15.0.0
  build_runner: ^2.4.13
  freezed: ^3.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
  plugin:
    platforms:
      linux:
        ffiPlugin: true
        
ffigen:
  name: 'PulseAudioBindings'
  description: 'Bindings for PulseAudio'
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '/usr/include/pulse/pulseaudio.h'
    include-directives:
      - /usr/include/**/**  # Include standard headers
  compiler-opts:
    - '-I/usr/lib/clang/18/include/'
